const HData = [
    {
        id: 1,
        himage: "House/1bhk9k.jpg",
        hrent: "9,000",
        hprice: " 32 lakhs",
        hname: "MilGrey Villa",
        hlocation: "C-202, alpha-1, Greater Noida, UP",
        hbed: "1 Bed",
        hbath: "1 Bathroom",
        harea: "13x13 ",
        htype: "1-BHK",
        hptype: "Rs.30 L - Rs.35 L",
        hrtype: "Rs.8 K - Rs.10 K",
        allrent: "All",
        alltype: "All",
        allprice: "All",
    },
    {
        id: 2,
        himage: "House/1bhk15k.jpg",
        hrent: "15,000",
        hprice: " 38 lakhs",
        hname: "MilGrey Villa",
        hlocation: "C-202, alpha-1, Greater Noida, UP",
        hbed: "1 Bed",
        hbath: "1 Bathroom",
        harea: "15x15 ",
        htype: "1-BHK",
        hptype: "Rs.35 L - Rs.45 L",
        hrtype: "Rs.10 K - Rs.18 K",
        allrent: "All",
        alltype: "All",
        allprice: "All",
    },
    {
        id: 3,
        himage: "House/1bhk25k.jpg",
        hrent: "25,000",
        hprice: " 50 lakhs",
        hname: "Woodgrey Villa",
        hlocation: "C-203, alpha-1, Greater Noida, UP",
        hbed: "1 Bed",
        hbath: "1 Bathroom",
        harea: "17x17 ",
        htype: "1-BHK",
        hptype: "Rs.45 L - Rs.65 L",
        hrtype: "Rs.18 K - Rs.25 K",
        allrent: "All",
        alltype: "All",
        allprice: "All",
    },
    {
        id: 4,
        himage: "House/1bhk34k.jpg",
        hrent: "34,000",
        hprice: " 58 lakhs",
        hname: "Whitewood Villa",
        hlocation: "C-203, alpha-1, Greater Noida, UP",
        hbed: "1 Beds",
        hbath: "1 Bathrooms",
        harea: "20x20",
        htype: "1-BHK",
        hptype: "Rs.45 L - Rs.65 L",
        hrtype: "Rs.25 K - Rs.35 K",
        allrent: "All",
        alltype: "All",
        allprice: "All",
    },
    {
        id: 5,
        himage: "House/2bhk10k.jpg",
        hrent: "10,000",
        hprice: " 35 lakhs",
        hname: "Blink Villa",
        hlocation: "a-201, alpha-2, Greater Noida, UP",
        hbed: "2 Beds",
        hbath: "2 Bathrooms",
        harea: "15x15",
        htype: "2-BHK",
        hptype: "Rs.30 L - Rs.35 L",
        hrtype: "Rs.8 K - Rs.10 K",
        allrent: "All",
        alltype: "All",
        allprice: "All",
    },
    {
        id: 6,
        himage: "House/2bhk18k.jpg",
        hrent: "18,000",
        hprice: " 40 lakhs",
        hname: "fancy Villa",
        hlocation: "a-202, alpha-2, Greater Noida, UP",
        hbed: "2 Beds",
        hbath: "2 Bathrooms",
        harea: "18x18",
        htype: "2-BHK",
        hptype: "Rs.35 L - Rs.45 L",
        hrtype: "Rs.10 K - Rs.18 K",
        allrent: "All",
        alltype: "All",
        allprice: "All",
    },
    {
        id: 7,
        himage: "House/2bhk24k.jpeg",
        hrent: "24,000",
        hprice: " 50 lakhs",
        hname: "Mavit Villa",
        hlocation: "a-203, alpha-2, Greater Noida, UP",
        hbed: "2 Beds",
        hbath: "2 Bathrooms",
        harea: "22x22",
        htype: "2-BHK",
        hptype: "Rs.45 L - Rs.65 L",
        hrtype: "Rs.18 K - Rs.25 K",
        allrent: "All",
        alltype: "All",
        allprice: "All",
    },
    {
        id: 8,
        himage: "House/2bhk34k.png",
        hrent: "34,000",
        hprice: " 58 lakhs",
        hname: "Yelwy Villa",
        hlocation: "a-204, alpha-2, Greater Noida, UP",
        hbed: "2 Beds",
        hbath: "2 Bathrooms",
        harea: "25x25",
        htype: "2-BHK",
        hptype: "Rs.45 L - Rs.65 L",
        hrtype: "Rs.25 K - Rs.35 K",
        allrent: "All",
        alltype: "All",
        allprice: "All",
    },
    {
        id: 9,
        himage: "House/3bhk18k.jpg",
        hrent: "18,000",
        hprice: " 43 lakhs",
        hname: "Rogrey Villa",
        hlocation: "b-201, Chi-Pi-2, Greater Noida, UP",
        hbed: "3 Beds",
        hbath: "3 Bathrooms",
        harea: "20x20",
        htype: "3-BHK",
        hptype: "Rs.35 L - Rs.45 L",
        hrtype: "Rs.10 K - Rs.18 K",
        allrent: "All",
        alltype: "All",
        allprice: "All",
    },
    {
        id: 10,
        himage: "House/3bhk25k.jpg",
        hrent: "25,000",
        hprice: " 50 lakhs",
        hname: "finley Villa",
        hlocation: "B-202, Chi-Pi-2, Greater Noida, UP",
        hbed: "3 Beds",
        hbath: "3 Bathrooms",
        harea: "25x25",
        htype: "3-BHK",
        hptype: "Rs.45 L - Rs.65 L",
        hrtype: "Rs.18 K - Rs.25 K",
        allrent: "All",
        alltype: "All",
        allprice: "All",
    },
    {
        id: 11,
        himage: "House/3bhk35k.jpg",
        hrent: "35,000",
        hprice: " 64 lakhs",
        hname: "marbol Villa",
        hlocation: "B-203, Chi-Pi-2, Greater Noida, UP",
        hbed: "3 Beds",
        hbath: "3 Bathrooms",
        harea: "30x30",
        htype: "3-BHK",
        hptype: "Rs.45 L - Rs.65 L",
        hrtype: "Rs.25 K - Rs.35 K",
        allrent: "All",
        alltype: "All",
        allprice: "All",
    }
]

export default HData;